spring.application.name=alert_monitor

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:alertdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 console (acessível em /h2-console no browser)
spring.h2.console.enabled=true